EVAL_CROP_SIZE: (512, 512) # (width, height), for unpadding rangescaling and stepscaling
TRAIN_CROP_SIZE: (512, 512) # (width, height), for unpadding rangescaling and stepscaling
AUG:
    AUG_METHOD: "stepscaling" # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: (640, 640) # (width, height), for unpadding
    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling
    MAX_SCALE_FACTOR: 2.0  # for stepscaling
    MIN_SCALE_FACTOR: 0.5  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling
    MIRROR: True
    FLIP: False
    FLIP_RATIO: 0.2
    RICH_CROP:
        ENABLE: False
        ASPECT_RATIO: 0.0
        BLUR: False
        BLUR_RATIO: 0.1
        MAX_ROTATION: 0
        MIN_AREA_RATIO: 0.0
        BRIGHTNESS_JITTER_RATIO: 0.0
        CONTRAST_JITTER_RATIO: 0.0
        SATURATION_JITTER_RATIO: 0.0
BATCH_SIZE: 12
MEAN: [0.5]
STD: [0.5]

DATASET:
    DATA_DIR: "./dataset/ncp-01/"
    IMAGE_TYPE: "rgb"  # choice rgb or rgba
    NUM_CLASSES: 2
    TEST_FILE_LIST: "dataset/ncp-01/val.txt"
    TRAIN_FILE_LIST: "dataset/ncp-01/train.txt"
    VAL_FILE_LIST: "dataset/ncp-01/val.txt"
    IGNORE_INDEX: 255
    DATA_DIM: 1

FREEZE:
    MODEL_FILENAME: "model"
    PARAMS_FILENAME: "params"
MODEL:
    DEFAULT_NORM_TYPE: "bn"
    MODEL_NAME: "unet"

TEST:
    TEST_MODEL: "snapshots/cityscape_fast_scnn/final/"
TRAIN:
    MODEL_SAVE_DIR: "snapshots/cityscape_fast_scnn/"
    SNAPSHOT_EPOCH: 10
SOLVER:
    LR: 0.045
    LR_POLICY: "poly"
    OPTIMIZER: "sgd"
    NUM_EPOCHS: 100
